image: node:latest

cache:
  key: "${CI_COMMIT_SHA}"
  untracked: true
  paths:
    - node_modules/

stages:
  - inception
  - assess
  - test
  - assemble

create-cache:
  stage: inception
  script:
    - npm install
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: push
    untracked: true
    paths:
    - node_modules/

assess:
  stage: assess
  script:
    - npm run lint
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm test
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - node_modules/

pack:
  stage: assemble
  script:
    - mkdir -p build
    - cd build
    - npm pack ../
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - node_modules/
  artifacts:
    name: $CI_PROJECT_NAME-$(date +%Y%m%d-%H%M)-$CI_COMMIT_SHORT_SHA
    paths:
      - .build/*.tgz
